/* tslint:disable */
/* eslint:disable */
// autogenerated by sequelize-pg-generator@0.0.1

import Sequelize = require('sequelize');

export default (sequelize: Sequelize.Sequelize): void => {
	const models = sequelize.models;
	
	// comment.author_id -> author.id (comment_author_id_fk)
	models.Comment.belongsTo(models.Author, { foreignKey: 'author_id', as: 'author' });

	// comment.post_id -> post.id (comment_post_id_fk)
	models.Comment.belongsTo(models.Post, { foreignKey: 'post_id', as: 'post' });

	// post.author_id -> author.id (post_author_id_fk)
	models.Post.belongsTo(models.Author, { foreignKey: 'author_id', as: 'author' });

	// post_category.category_id -> category.id (post_category_category_id_fk)
	models.Category.belongsToMany(models.Post, { through: models.PostCategory, foreignKey: 'category_id' });

	// post_category.post_id -> post.id (post_category_post_id_fk)
	models.Post.belongsToMany(models.Category, { through: models.PostCategory, foreignKey: 'post_id' });
};
