/* tslint:disable */
/* eslint:disable */
// autogenerated by sequelize-pg-generator@0.0.1

import Sequelize = require('sequelize');
import { DataTypes, DefineAttributes, DefineOptions } from 'sequelize';


export interface PostCategoryAttributes {
	postId: number
	categoryId: number
}

export interface PostCategory extends Sequelize.Instance<PostCategoryAttributes>, PostCategoryAttributes {

}

export default (
	sequelize: Sequelize.Sequelize,
	tableOptions?: DefineOptions<PostCategory>
): Sequelize.Model<PostCategory, PostCategoryAttributes> => {
	const DataTypes: DataTypes = sequelize.Sequelize;

	tableOptions = tableOptions || {};
	tableOptions.freezeTableName = true;
	tableOptions.tableName = 'post_category';

	const columns: DefineAttributes = {
		postId: {
			field: 'post_id',
			type: DataTypes.INTEGER /* integer */,
			primaryKey: true,
			allowNull: false,
			autoIncrement: false
		},
		categoryId: {
			field: 'category_id',
			type: DataTypes.INTEGER /* integer */,
			primaryKey: true,
			allowNull: false,
			autoIncrement: false
		}
	};

	return sequelize.define<PostCategory, PostCategoryAttributes>(
		'PostCategory',
		columns,
		tableOptions
	);
};
