/* tslint:disable */
/* eslint:disable */
// autogenerated by sequelize-pg-generator@0.0.1

import Sequelize = require('sequelize');
import { DataTypes, DefineAttributes, DefineOptions, FindOptions } from 'sequelize';
import { Author } from './author';
import { Category } from './category';

export interface PostAttributes {
	id: number
	authorId: number
	title: string
	content: string
	createdAt: Date
	publishedAt: Date
}

export interface Post extends Sequelize.Instance<PostAttributes>, PostAttributes {
	author: Author | null
	getCategories: (options?: FindOptions<Category>) => Promise<Category[]>
	setCategories: (categories: Category[]) => Promise<void>
	addCategory: (category: Category) => Promise<void>
	addCategories: (categories: Category[]) => Promise<void>
}

export default (
	sequelize: Sequelize.Sequelize,
	tableOptions?: DefineOptions<Post>
): Sequelize.Model<Post, PostAttributes> => {
	const DataTypes: DataTypes = sequelize.Sequelize;

	tableOptions = tableOptions || {};
	tableOptions.freezeTableName = true;
	tableOptions.tableName = 'post';

	const columns: DefineAttributes = {
		id: {
			field: 'id',
			type: DataTypes.INTEGER /* integer */,
			primaryKey: true,
			allowNull: false,
			autoIncrement: true
		},
		authorId: {
			field: 'author_id',
			type: DataTypes.INTEGER /* integer */,
			primaryKey: false,
			allowNull: false,
			autoIncrement: false
		},
		title: {
			field: 'title',
			type: DataTypes.STRING(255) /* character varying */,
			primaryKey: false,
			allowNull: false,
			autoIncrement: false
		},
		content: {
			field: 'content',
			type: DataTypes.TEXT /* text */,
			primaryKey: false,
			allowNull: true,
			autoIncrement: false
		},
		createdAt: {
			field: 'created_at',
			type: DataTypes.DATE /* timestamp with time zone */,
			primaryKey: false,
			allowNull: false,
			autoIncrement: false,
			defaultValue: DataTypes.NOW
		},
		publishedAt: {
			field: 'published_at',
			type: DataTypes.DATE /* timestamp with time zone */,
			primaryKey: false,
			allowNull: true,
			autoIncrement: false
		}
	};

	return sequelize.define<Post, PostAttributes>(
		'Post',
		columns,
		tableOptions
	);
};
